name: Build

on:
  push:
    branches:
      - main
      - "feature/**"
      - "fix/**"
      - "docs/**"
      - "refactor/**"

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Solution
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore Deadbelt.OperationsPlatform.sln

      - name: Build
        run: dotnet build Deadbelt.OperationsPlatform.sln --configuration Release --no-restore